<?php

namespace ContainerGOWBse0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LM0KWXRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LM0KWXR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LM0KWXR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'filmeRepository' => ['privates', 'App\\Repository\\FilmeRepository', 'getFilmeRepositoryService', true],
        ], [
            'entityManager' => '?',
            'filmeRepository' => 'App\\Repository\\FilmeRepository',
        ]);
    }
}
