<?php

namespace ContainerGOWBse0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2fOLRlR.App\Entity\Categoria' shared service.
     *
     * @return \App\Entity\Categoria
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.2fOLRlR": it needs an instance of "App\\Entity\\Categoria" but this type has been excluded in "config/services.yaml".');
    }
}
