<?php

namespace ContainerGOWBse0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhotosService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.h3KQSkK.App\Entity\Photos' shared service.
     *
     * @return \App\Entity\Photos
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.h3KQSkK": it needs an instance of "App\\Entity\\Photos" but this type has been excluded in "config/services.yaml".');
    }
}
