<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Filme extends \App\Entity\Filme implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categoria' => [parent::class, 'categoria', null],
        "\0".parent::class."\0".'descricao' => [parent::class, 'descricao', null],
        "\0".parent::class."\0".'foto' => [parent::class, 'foto', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'photos' => [parent::class, 'photos', null],
        "\0".parent::class."\0".'titulo' => [parent::class, 'titulo', null],
        'categoria' => [parent::class, 'categoria', null],
        'descricao' => [parent::class, 'descricao', null],
        'foto' => [parent::class, 'foto', null],
        'id' => [parent::class, 'id', null],
        'photos' => [parent::class, 'photos', null],
        'titulo' => [parent::class, 'titulo', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
