<?php

namespace ContainerCRScDmO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JsxmPbGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jsxmPbG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jsxmPbG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorium' => ['privates', '.errored..service_locator.jsxmPbG.App\\Entity\\Categoria', NULL, 'Cannot autowire service ".service_locator.jsxmPbG": it needs an instance of "App\\Entity\\Categoria" but this type has been excluded in "config/services.yaml".'],
        ], [
            'categorium' => 'App\\Entity\\Categoria',
        ]);
    }
}
