<?php

namespace ContainerCRScDmO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AlV44vyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AlV44vy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AlV44vy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CategoriasController::delete' => ['privates', '.service_locator.2fOLRlR', 'get_ServiceLocator_2fOLRlRService', true],
            'App\\Controller\\CategoriasController::deleteConfirmation' => ['privates', '.service_locator.2fOLRlR', 'get_ServiceLocator_2fOLRlRService', true],
            'App\\Controller\\CategoriasController::edit' => ['privates', '.service_locator.2fOLRlR', 'get_ServiceLocator_2fOLRlRService', true],
            'App\\Controller\\CategoriasController::index' => ['privates', '.service_locator.Ecpu4I3', 'get_ServiceLocator_Ecpu4I3Service', true],
            'App\\Controller\\CategoriasController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategoriasController::show' => ['privates', '.service_locator.jsxmPbG', 'get_ServiceLocator_JsxmPbGService', true],
            'App\\Controller\\FilmesController::delete' => ['privates', '.service_locator.UHIGg53', 'get_ServiceLocator_UHIGg53Service', true],
            'App\\Controller\\FilmesController::deleteConfirmation' => ['privates', '.service_locator.UHIGg53', 'get_ServiceLocator_UHIGg53Service', true],
            'App\\Controller\\FilmesController::edit' => ['privates', '.service_locator.UHIGg53', 'get_ServiceLocator_UHIGg53Service', true],
            'App\\Controller\\FilmesController::index' => ['privates', '.service_locator.LM0KWXR', 'get_ServiceLocator_LM0KWXRService', true],
            'App\\Controller\\FilmesController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\FilmesController::show' => ['privates', '.service_locator.UHIGg53', 'get_ServiceLocator_UHIGg53Service', true],
            'App\\Controller\\MailController::sendEmail' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\PhotosController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UsersController::edit' => ['privates', '.service_locator.R0Sb2kd', 'get_ServiceLocator_R0Sb2kdService', true],
            'App\\Controller\\UsersController::index' => ['privates', '.service_locator.Ecpu4I3', 'get_ServiceLocator_Ecpu4I3Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CategoriasController:delete' => ['privates', '.service_locator.2fOLRlR', 'get_ServiceLocator_2fOLRlRService', true],
            'App\\Controller\\CategoriasController:deleteConfirmation' => ['privates', '.service_locator.2fOLRlR', 'get_ServiceLocator_2fOLRlRService', true],
            'App\\Controller\\CategoriasController:edit' => ['privates', '.service_locator.2fOLRlR', 'get_ServiceLocator_2fOLRlRService', true],
            'App\\Controller\\CategoriasController:index' => ['privates', '.service_locator.Ecpu4I3', 'get_ServiceLocator_Ecpu4I3Service', true],
            'App\\Controller\\CategoriasController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategoriasController:show' => ['privates', '.service_locator.jsxmPbG', 'get_ServiceLocator_JsxmPbGService', true],
            'App\\Controller\\FilmesController:delete' => ['privates', '.service_locator.UHIGg53', 'get_ServiceLocator_UHIGg53Service', true],
            'App\\Controller\\FilmesController:deleteConfirmation' => ['privates', '.service_locator.UHIGg53', 'get_ServiceLocator_UHIGg53Service', true],
            'App\\Controller\\FilmesController:edit' => ['privates', '.service_locator.UHIGg53', 'get_ServiceLocator_UHIGg53Service', true],
            'App\\Controller\\FilmesController:index' => ['privates', '.service_locator.LM0KWXR', 'get_ServiceLocator_LM0KWXRService', true],
            'App\\Controller\\FilmesController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\FilmesController:show' => ['privates', '.service_locator.UHIGg53', 'get_ServiceLocator_UHIGg53Service', true],
            'App\\Controller\\MailController:sendEmail' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\PhotosController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UsersController:edit' => ['privates', '.service_locator.R0Sb2kd', 'get_ServiceLocator_R0Sb2kdService', true],
            'App\\Controller\\UsersController:index' => ['privates', '.service_locator.Ecpu4I3', 'get_ServiceLocator_Ecpu4I3Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CategoriasController::delete' => '?',
            'App\\Controller\\CategoriasController::deleteConfirmation' => '?',
            'App\\Controller\\CategoriasController::edit' => '?',
            'App\\Controller\\CategoriasController::index' => '?',
            'App\\Controller\\CategoriasController::new' => '?',
            'App\\Controller\\CategoriasController::show' => '?',
            'App\\Controller\\FilmesController::delete' => '?',
            'App\\Controller\\FilmesController::deleteConfirmation' => '?',
            'App\\Controller\\FilmesController::edit' => '?',
            'App\\Controller\\FilmesController::index' => '?',
            'App\\Controller\\FilmesController::new' => '?',
            'App\\Controller\\FilmesController::show' => '?',
            'App\\Controller\\MailController::sendEmail' => '?',
            'App\\Controller\\PhotosController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UsersController::edit' => '?',
            'App\\Controller\\UsersController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategoriasController:delete' => '?',
            'App\\Controller\\CategoriasController:deleteConfirmation' => '?',
            'App\\Controller\\CategoriasController:edit' => '?',
            'App\\Controller\\CategoriasController:index' => '?',
            'App\\Controller\\CategoriasController:new' => '?',
            'App\\Controller\\CategoriasController:show' => '?',
            'App\\Controller\\FilmesController:delete' => '?',
            'App\\Controller\\FilmesController:deleteConfirmation' => '?',
            'App\\Controller\\FilmesController:edit' => '?',
            'App\\Controller\\FilmesController:index' => '?',
            'App\\Controller\\FilmesController:new' => '?',
            'App\\Controller\\FilmesController:show' => '?',
            'App\\Controller\\MailController:sendEmail' => '?',
            'App\\Controller\\PhotosController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UsersController:edit' => '?',
            'App\\Controller\\UsersController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
