<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGOWBse0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGOWBse0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGOWBse0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGOWBse0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGOWBse0\App_KernelDevDebugContainer([
    'container.build_hash' => 'GOWBse0',
    'container.build_id' => 'beb8c3fe',
    'container.build_time' => 1697069937,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGOWBse0');
