<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX3wx3px\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX3wx3px/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX3wx3px.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX3wx3px\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX3wx3px\App_KernelDevDebugContainer([
    'container.build_hash' => 'X3wx3px',
    'container.build_id' => '8010e3f5',
    'container.build_time' => 1697500806,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX3wx3px');
